name: Generate Repository XML and Upload to MinIO via Cloudflare

on:
  push:
    branches:
      - main
    paths:
      - "src/site/notes/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/site/notes/**"

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Клонує репозиторій з усіма файлами

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
        # Встановлює unzip для розпакування AWS CLI

      - name: Pack repository with Repomix
        uses: yamadashy/repomix/.github/actions/repomix@main
        with:
          output: repository.xml
          additional-args: --config repomix.config.json
        # Використовує дію repomix із конфігураційним файлом

      - name: Verify generated XML
        run: |
          if [ ! -s repository.xml ]; then
            echo "Помилка: XML-файл порожній або не створений"
            exit 1
          fi
          echo "Згенеровано repository.xml розміром $(stat -c%s repository.xml) байт"
        # Перевіряє, що XML-файл створено і не порожній

      - name: Upload Repomix output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-xml
          path: repository.xml
          retention-days: 7
        # Завантажує XML як артефакт для дебагінгу

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        # Встановлює AWS CLI для роботи з MinIO

      - name: Configure AWS CLI for MinIO via Cloudflare
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region us-east-1
          aws configure set default.s3.addressing_style path
        # Налаштовує AWS CLI для MinIO через Cloudflare

      - name: Upload Repository XML to MinIO
        env:
          AWS_S3_DISABLE_MULTIPART: "1"
        shell: bash
        run: |
          echo "Uploading repository.xml to MinIO via Cloudflare Tunnel"
          
          aws --endpoint-url https://apiminio.exodus.pp.ua \
    s3api put-object \
    --bucket exodusppua \
    --key "repository.xml" \
    --body "repository.xml" \
    --content-type application/xml \
    --cli-read-timeout 600 \
    --cli-connect-timeout 600 \
    --no-verify-ssl \
    --debug


          if [[ $? -ne 0 ]]; then
            echo "Помилка під час завантаження XML"
            exit 1
          fi

          echo "✓ Успішно завантажено: repository.xml"
        # Завантажує XML на MinIO і перевіряє результат
