      - name: Update PDF records in Noco-DB
        env:
          NOCO_DB_API_URL: "https://nocodb.soyka.pp.ua"
          NOCO_DB_TABLE_ID: "m3plh50uwtk34zd"
          NOCO_DB_VIEW_ID: "vwtr2835wqny8msk"
          NOCO_DB_API_TOKEN: ${{ secrets.NOCO_DB_API_KEY }}
        run: |
          echo "Processing PDF files for Noco-DB update..."
          for pdf in src/site/notes/*.pdf; do
            filename=$(basename "$pdf")
            echo "Processing file: $filename"
            # URL-енкодимо ім'я файлу, щоб уникнути проблем із спецсимволами
            encoded_filename=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$filename")
            
            # Виконуємо GET-запит з URL-кодованим ім'ям файлу
            record=$(curl -s --request GET \
              --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records?where=filename,eq,$encoded_filename" \
              --header "xc-token: $NOCO_DB_API_TOKEN")
              
            if echo "$record" | grep -q '"data":\[\]'; then
              echo "Record for $filename not found. Creating a new record..."
              curl --request POST \
                --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
                --header "xc-token: $NOCO_DB_API_TOKEN" \
                -F "filename=$filename" \
                -F "file=@$pdf"
            else
              recordId=$(echo "$record" | jq -r '.data[0].id')
              echo "Record for $filename exists (ID: $recordId). Updating the record..."
              curl --request PATCH \
                --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records/$recordId" \
                --header "xc-token: $NOCO_DB_API_TOKEN" \
                -F "filename=$filename" \
                -F "file=@$pdf"
            fi
          done
