name: Generate PDF and Upload to MinIO via Cloudflare (one-by-one, put-object)

on:
  push:
    branches:
      - main
    paths:
      - "src/site/notes/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/site/notes/**"

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            shared-mime-info \
            unzip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown weasyprint beautifulsoup4

      - name: Generate PDFs per topic
        run: |
          printf "src/site/notes\n\n\n" | python codetomd.py

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS CLI for MinIO via Cloudflare
        env:
          AWS_ACCESS_KEY_ID: 77icD4OgvRKPKF198eiC
          AWS_SECRET_ACCESS_KEY: B3kWQMmF4zZLb9W6dboJrdDQAMWBrVyAG4ySFBIx
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region us-east-1
          aws configure set default.s3.addressing_style path

      - name: Upload PDFs to MinIO (put-object, simple rename)
        env:
          AWS_S3_DISABLE_MULTIPART: "1"
        shell: bash
        run: |
          echo "Uploading PDF files to MinIO via Cloudflare Tunnel (using s3api put-object, one-by-one)"
          
          # Знайти всі PDF у каталозі src/site/notes
          mapfile -t pdf_files < <(find src/site/notes -type f -iname "*.pdf")
          
          for pdf in "${pdf_files[@]}"; do
            orig_name="$(basename "$pdf")"
            
            # Видаляємо всі символи, окрім літер (лат/кир), цифр, . _ - та пробілів,
            # а потім пробіли замінюємо на дефіси.
            safe_name="$(
              echo "$orig_name" \
                | LC_ALL=en_US.UTF-8 sed -E 's/[^-[:alnum:]А-Яа-яЁёІіЇїЄєҐґ._ ]//g' \
                | sed 's/ /-/g'
            )"
            
            echo "→ Original: $orig_name"
            echo "→ Cleaned : $safe_name"
            
            aws --endpoint-url https://apiminio.exodus.pp.ua \
                s3api put-object \
                --bucket exodusbase \
                --key "$safe_name" \
                --body "$pdf" \
                --content-type application/pdf \
                --cli-read-timeout 360 \
                --cli-connect-timeout 360
            
            if [[ $? -ne 0 ]]; then
              echo "Помилка під час завантаження: $orig_name"
              exit 1
            fi
          done
          
          echo "Успішно завантажено PDF-файли."
