 name: Update PDF records in Noco-DB
  env:
    NOCO_DB_API_URL: "https://nocodb.soyka.pp.ua"
    NOCO_DB_TABLE_ID: "m3plh50uwtk34zd"
    NOCO_DB_VIEW_ID: "vwtr2835wqny8msk"
    NOCO_DB_API_TOKEN: ${{ secrets.NOCO_DB_API_KEY }}
  run: |
    echo "Processing PDF files for Noco-DB update..."
    
    for pdf in src/site/notes/*.pdf; do
      filename=$(basename "$pdf")
      echo "Processing file: $filename"
      
      # 1. Завантаження файлу через окремий ендпоінт
      upload_response=$(curl -s --request POST \
        --url "$NOCO_DB_API_URL/api/v1/db/storage/upload" \
        --header "xc-token: $NOCO_DB_API_TOKEN" \
        -F "file=@$pdf")
      
      file_url=$(echo "$upload_response" | jq -r '.url')
      file_title=$(echo "$upload_response" | jq -r '.title')
      
      # 2. Перевірка успішності завантаження
      if [[ "$file_url" == "null" || -z "$file_url" ]]; then
        echo "File upload failed for $filename"
        continue
      fi
      
      # 3. Пошук існуючого запису з viewId
      existing_record=$(curl -s --request GET \
        --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records?where=(filename,eq,$filename)&viewId=$NOCO_DB_VIEW_ID" \
        --header "xc-token: $NOCO_DB_API_TOKEN")
      
      # 4. Обробка відповідно до API схеми
      if echo "$existing_record" | jq -e '.list | length == 0' > /dev/null; then
        # CREATE
        curl --request POST \
          --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
          --header "xc-token: $NOCO_DB_API_TOKEN" \
          --header "Content-Type: application/json" \
          --data "{
            \"filename\": \"$filename\",
            \"PDF\": [{
              \"url\": \"$file_url\",
              \"title\": \"$file_title\",
              \"mimetype\": \"application/pdf\"
            }]
          }"
      else
        # UPDATE
        record_id=$(echo "$existing_record" | jq -r '.list[0].Id')
        
        curl --request PATCH \
          --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
          --header "xc-token: $NOCO_DB_API_TOKEN" \
          --header "Content-Type: application/json" \
          --data "{
            \"Id\": $record_id,
            \"PDF\": [{
              \"url\": \"$file_url\", 
              \"title\": \"$file_title\",
              \"mimetype\": \"application/pdf\"
            }]
          }"
      fi
    done- name: Update PDF records in Noco-DB
  env:
    NOCO_DB_API_URL: "https://nocodb.soyka.pp.ua"
    NOCO_DB_TABLE_ID: "m3plh50uwtk34zd"
    NOCO_DB_VIEW_ID: "vwtr2835wqny8msk"
    NOCO_DB_API_TOKEN: ${{ secrets.NOCO_DB_API_KEY }}
  run: |
    echo "Processing PDF files for Noco-DB update..."
    
    for pdf in src/site/notes/*.pdf; do
      filename=$(basename "$pdf")
      echo "Processing file: $filename"
      
      # 1. Завантаження файлу через окремий ендпоінт
      upload_response=$(curl -s --request POST \
        --url "$NOCO_DB_API_URL/api/v1/db/storage/upload" \
        --header "xc-token: $NOCO_DB_API_TOKEN" \
        -F "file=@$pdf")
      
      file_url=$(echo "$upload_response" | jq -r '.url')
      file_title=$(echo "$upload_response" | jq -r '.title')
      
      # 2. Перевірка успішності завантаження
      if [[ "$file_url" == "null" || -z "$file_url" ]]; then
        echo "File upload failed for $filename"
        continue
      fi
      
      # 3. Пошук існуючого запису з viewId
      existing_record=$(curl -s --request GET \
        --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records?where=(filename,eq,$filename)&viewId=$NOCO_DB_VIEW_ID" \
        --header "xc-token: $NOCO_DB_API_TOKEN")
      
      # 4. Обробка відповідно до API схеми
      if echo "$existing_record" | jq -e '.list | length == 0' > /dev/null; then
        # CREATE
        curl --request POST \
          --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
          --header "xc-token: $NOCO_DB_API_TOKEN" \
          --header "Content-Type: application/json" \
          --data "{
            \"filename\": \"$filename\",
            \"PDF\": [{
              \"url\": \"$file_url\",
              \"title\": \"$file_title\",
              \"mimetype\": \"application/pdf\"
            }]
          }"
      else
        # UPDATE
        record_id=$(echo "$existing_record" | jq -r '.list[0].Id')
        
        curl --request PATCH \
          --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
          --header "xc-token: $NOCO_DB_API_TOKEN" \
          --header "Content-Type: application/json" \
          --data "{
            \"Id\": $record_id,
            \"PDF\": [{
              \"url\": \"$file_url\", 
              \"title\": \"$file_title\",
              \"mimetype\": \"application/pdf\"
            }]
          }"
      fi
    done
