name: Generate PDF

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/site/notes/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/site/notes/**"

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            shared-mime-info

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown weasyprint beautifulsoup4

      - name: Generate PDFs per topic
        run: |
          # Передаємо:
          # 1. Базову директорію з нотатками (src/site/notes)
          # 2. Порожній рядок для output_dir – за замовчуванням буде базова директорія
          # 3. Порожній рядок для додаткових ігнорованих папок
          printf "src/site/notes\n\n\n" | python codetomd.py

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: src/site/notes/*.pdf