name: Generate PDF and Update Noco-DB

on:
  push:
    branches:
      - main
    paths:
      - "src/site/notes/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/site/notes/**"

jobs:
  generate-and-update-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            shared-mime-info \
            jq

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown weasyprint beautifulsoup4 requests

      - name: Generate PDFs per topic
        run: |
          printf "src/site/notes\n\n\n" | python codetomd.py

      - name: Update PDF records in Noco-DB
        env:
          NOCO_DB_API_URL: "https://nocodb.soyka.pp.ua"
          NOCO_DB_TABLE_ID: "m3plh50uwtk34zd"
          NOCO_DB_VIEW_ID: "vwtr2835wqny8msk"
          NOCO_DB_API_TOKEN: ${{ secrets.NOCO_DB_API_KEY }}
        run: |
          echo "Processing PDF files for Noco-DB update..."

          for pdf in src/site/notes/*.pdf; do
            filename=$(basename "$pdf")
            echo "Processing file: $filename"

            # URL-кодуємо ім'я файлу
            encoded_filename=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$filename")

            # Отримуємо запис із NocoDB
            response=$(curl -s --request GET \
              --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records?where=(filename,eq,$encoded_filename)&viewId=$NOCO_DB_VIEW_ID" \
              --header "xc-token: $NOCO_DB_API_TOKEN")

            # Перевіряємо, чи запис існує
            if echo "$response" | jq -e '.data | length == 0' > /dev/null; then
              echo "Record for $filename not found. Creating a new record..."

              # Завантажуємо файл до NocoDB
              file_upload_response=$(curl -s --request POST \
                --url "$NOCO_DB_API_URL/api/v1/db/storage/upload" \
                --header "xc-token: $NOCO_DB_API_TOKEN" \
                -F "file=@$pdf")

              file_url=$(echo "$file_upload_response" | jq -r '.url')

              if [[ -z "$file_url" || "$file_url" == "null" ]]; then
                echo "Error: Failed to upload file."
                continue
              fi

              # Створюємо новий запис
              attempt=0
              max_attempts=3
              while [ $attempt -lt $max_attempts ]; do
                response=$(curl --silent --show-error --fail --request POST \
                  --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records" \
                  --header "xc-token: $NOCO_DB_API_TOKEN" \
                  --header "Content-Type: application/json" \
                  --data "{\"filename\": \"$filename\", \"PDF\": [{\"url\": \"$file_url\"}]}")

                if [[ $? -eq 0 ]]; then
                  echo "Successfully created record for $filename"
                  break
                fi

                attempt=$((attempt+1))
                echo "Retrying... ($attempt/$max_attempts)"
                sleep 2
              done
            else
              recordId=$(echo "$response" | jq -r '.data[0].Id')

              if [[ "$recordId" == "null" ]]; then
                echo "Error: recordId is null, skipping PATCH for $filename"
                continue
              fi

              echo "Record for $filename exists (ID: $recordId). Updating the record..."

              # Завантажуємо новий файл до NocoDB
              file_upload_response=$(curl -s --request POST \
                --url "$NOCO_DB_API_URL/api/v1/db/storage/upload" \
                --header "xc-token: $NOCO_DB_API_TOKEN" \
                -F "file=@$pdf")

              file_url=$(echo "$file_upload_response" | jq -r '.url')

              if [[ -z "$file_url" || "$file_url" == "null" ]]; then
                echo "Error: Failed to upload file."
                continue
              fi

              # Оновлюємо запис
              attempt=0
              max_attempts=3
              while [ $attempt -lt $max_attempts ]; do
                response=$(curl --silent --show-error --fail --request PATCH \
                  --url "$NOCO_DB_API_URL/api/v2/tables/$NOCO_DB_TABLE_ID/records/$recordId" \
                  --header "xc-token: $NOCO_DB_API_TOKEN" \
                  --header "Content-Type: application/json" \
                  --data "{\"PDF\": [{\"url\": \"$file_url\"}]}")

                if [[ $? -eq 0 ]]; then
                  echo "Successfully updated record for $filename"
                  break
                fi

                attempt=$((attempt+1))
                echo "Retrying... ($attempt/$max_attempts)"
                sleep 2
              done
            fi
          done
