      - name: Upload PDFs to MinIO (put-object, simple rename)
        env:
          AWS_S3_DISABLE_MULTIPART: "1"
        shell: bash
        run: |
          echo "Uploading PDF files to MinIO via Cloudflare Tunnel (using s3api put-object, one-by-one)"
  
          # Знайти всі PDF у каталозі src/site/notes
          mapfile -t pdf_files < <(find src/site/notes -type f -iname "*.pdf")
  
          for pdf in "${pdf_files[@]}"; do
            orig_name="$(basename "$pdf")"
  
            # Видаляємо всі символи, окрім літер (латинських/кирилиці), цифр, . _ - та пробілів,
            # а потім пробіли замінюємо на дефіси.
            safe_name="$(
              echo "$orig_name" \
                | LC_ALL=en_US.UTF-8 sed -E 's/[^[:alnum:]А-Яа-яЁёІіЇїЄєҐґ._\- ]//g' \
                | sed 's/ /-/g'
            )"
  
            echo "→ Original: $orig_name"
            echo "→ Cleaned : $safe_name"
  
            aws --endpoint-url https://apiminio.exodus.pp.ua \
                s3api put-object \
                --bucket exodusbase \
                --key "$safe_name" \
                --body "$pdf" \
                --content-type application/pdf \
                --cli-read-timeout 360 \
                --cli-connect-timeout 360
  
            if [[ $? -ne 0 ]]; then
              echo "Помилка під час завантаження: $orig_name"
              exit 1
            fi
          done
  
          echo "Успішно завантажено PDF-файли."
